### ISSUE TITLE
Install Netlogo 5.3.1

### ISSUE THREAD

**Issue by tombro1987** [rcgsheffield/sheffield_hpc#390] opened 2016-10-19 15:15 UTC
Related to call reference F1854075 placed on 18/10/2016

**Comment by willfurnass** [comment] 2016-10-21 09:05
As discussed by email, I think that the relative ease of installing and using NetLogo from one's home directory and the availability of a [good user guide](https://ccl.northwestern.edu/netlogo/docs/) means that there's no need for NetLogo to be installed cluster-wide and referenced from this documentation.  However, feel free to reopen this issue if you disagree.

**Comment by tombro1987** [comment] 2016-10-21 13:35
Hi Will,

Apologies I feel there may have been a misunderstanding here. Netlogo is easily installed, and runs ok on the managed desktops at the uni. However my model has gotten quite complicated and computationally intensive, to the point where running it can take a whole day for a single model. My original enquiry was regarding the possibility of being able to run my model through Iceberg to speed the whole process up, and it was then that I was asked to log an issue on the HPC github page. I probably should have explained the situation in more detail at that point. 

I completely understand if you don't want to install Netlogo cluster-wide, and I agree it's relatively simple to get running. I suppose my question was more along the lines of whether I could use Iceberg, maybe as a one-off, to run my models. However I appreciate this then brings the topic back to installing Netlogo cluster-wide.

Apologies about all this,

Regards,

Tom

**Comment by mikecroucher** [comment] 2016-10-25 15:34
I've got Tom's code and will take a look.

**Comment by tombro1987** [comment] 2016-10-25 18:23
Hi Will,

Apologies I feel there may have been a misunderstanding here. Netlogo is
easily installed, and runs ok on the managed desktops at the uni. However
my model has gotten quite complicated and computationally intensive, to the
point where running it can take a whole day for a single model. My original
enquiry was regarding the possibility of being able to run my model through
Iceberg to speed the whole process up, and it was then that I was asked to
log an issue on the HPC github page. I probably should have explained the
situation in more detail at that point.

I completely understand if you don't want to install Netlogo cluster-wide,
and I agree it's relatively simple to get running. I suppose my question
was more along the lines of whether I could use Iceberg, maybe as a
one-off, to run my models. However I appreciate this then brings the topic
back to installing Netlogo cluster-wide.

Apologies about all this,

Regards,

Tom

**Comment by philmikejones** [comment] 2016-10-26 13:57
I had a look with Tom to install NetLogo on my user account to see if it worked. We managed to get a GUI working, but when trying to run it headless we ran into trouble. We used the following guide (see from 'Advanced Usage' onwards): http://ccl.northwestern.edu/netlogo/docs/behaviorspace.html

Our error: 
```
Error occurred during initialization of VM
Could not reserve enough space for object heap
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
```
Any ideas @mikecroucher @willfurnass ? Thanks.

**Comment by mikecroucher** [comment] 2016-10-27 09:12
Common problem with Java codes on Iceberg. You need to request more virtual memory
If you are running it in batch, add this to the top of your script

`#$ -l mem=9G -l rmem=9G`

If you are running interactively, you need to start your `qrshx` session like this:

`qrsh -l mem=9G -l rmem=9G`

Might need to play with the values a bit. The above are for 9 gigabytes

**Comment by philmikejones** [comment] 2016-10-27 11:19
Thanks @mikecroucher I'll work with @tombro1987 and give it a try early next week. Will let you know

**Comment by tombro1987** [comment] 2016-10-27 17:42
Thanks very much for your help @mikecroucher, hopefully get this working next week

**Comment by philmikejones** [comment] 2016-11-07 16:34
Hi @mikecroucher 
We tried your suggestions above to increase the RAM available but got the following error message:

```
qrsh -l mem=8GB -l rmem=8GB
attribute "h_vmem" is not a memory value
```
(It's the same whether I use `qrsh` or `qrshx` (whatever the difference is)).

Any other suggestions, or should we sit down with you and have a look at it?
Thanks.

**Comment by willfurnass** [comment] 2016-11-07 16:40
That's an unhelpful and odd error message.  You want `qrsh -l mem=8G -l rmem=8G` i.e. no `B`.

**Comment by philmikejones** [comment] 2016-11-07 16:58
Cheers @willfurnass , yep, that sorted it, thanks.

**Comment by tombro1987** [comment] 2016-11-07 17:17
Hi, we tried running the model on my machine and got the following error message:

```
Exception in thread "main" org.picocontainer.PicoCompositionException: java.lang.reflect.InvocationTargetException
        at org.picocontainer.injectors.ConstructorInjector$1.run(ConstructorInjector.java:343)
        at org.picocontainer.injectors.AbstractInjector$ThreadLocalCyclicDependencyGuard.observe(AbstractInjector.java:272)
        at org.picocontainer.injectors.ConstructorInjector.getComponentInstance(ConstructorInjector.java:354)
        at org.picocontainer.injectors.AbstractInjectionFactory$LifecycleAdapter.getComponentInstance(AbstractInjectionFactory.java:56)
        at org.picocontainer.behaviors.AbstractBehavior.getComponentInstance(AbstractBehavior.java:64)
        at org.picocontainer.behaviors.Stored.getComponentInstance(Stored.java:91)
        at org.picocontainer.DefaultPicoContainer.getInstance(DefaultPicoContainer.java:692)
        at org.picocontainer.DefaultPicoContainer.getComponent(DefaultPicoContainer.java:646)
        at org.picocontainer.DefaultPicoContainer.getComponent(DefaultPicoContainer.java:671)
        at org.nlogo.headless.HeadlessWorkspace$.newInstance(HeadlessWorkspace.scala:51)
        at org.nlogo.headless.HeadlessWorkspace$.newInstance(HeadlessWorkspace.scala:31)
        at org.nlogo.headless.Main$.newWorkspace$1(Main.scala:18)
        at org.nlogo.headless.Main$$anonfun$runExperiment$1.apply(Main.scala:24)
        at org.nlogo.headless.Main$$anonfun$runExperiment$1.apply(Main.scala:24)
        at org.nlogo.lab.Lab$$anonfun$1.apply(Lab.scala:33)
        at org.nlogo.lab.Lab$$anonfun$1.apply(Lab.scala:33)
        at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:233)
        at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:233)
        at scala.collection.immutable.Range.foreach(Range.scala:78)
        at scala.collection.TraversableLike$class.map(TraversableLike.scala:233)
        at scala.collection.immutable.Range.map(Range.scala:46)
        at org.nlogo.lab.Lab.run(Lab.scala:33)
        at org.nlogo.headless.Main$.runExperiment(Main.scala:24)
        at org.nlogo.headless.Main$$anonfun$main$1.apply(Main.scala:14)
        at org.nlogo.headless.Main$$anonfun$main$1.apply(Main.scala:14)
        at scala.Option.foreach(Option.scala:197)
        at org.nlogo.headless.Main$.main(Main.scala:14)
        at org.nlogo.headless.Main.main(Main.scala)
Caused by: java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
        at org.nlogo.util.Femto$.get(Femto.scala:16)
        at org.nlogo.util.Femto.get(Femto.scala)
        at org.nlogo.workspace.AbstractWorkspace.<init>(AbstractWorkspace.java:110)
        at org.nlogo.workspace.AbstractWorkspaceScala.<init>(AbstractWorkspaceScala.scala:19)
        at org.nlogo.headless.HeadlessWorkspace.<init>(HeadlessWorkspace.scala:101)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
        at org.picocontainer.injectors.AbstractInjector.newInstance(AbstractInjector.java:147)
        at org.picocontainer.injectors.ConstructorInjector$1.run(ConstructorInjector.java:332)
        ... 27 more
Caused by: java.lang.OutOfMemoryError: unable to create new native thread
        at java.lang.Thread.start0(Native Method)
        at java.lang.Thread.start(Thread.java:714)
        at org.nlogo.job.JobThread.<init>(JobThread.scala:49)
        at org.nlogo.job.JobManager.<init>(JobManager.scala:15)
        ... 42 more
```
Is it worth meeting together to try and get this working?

**Comment by mikecroucher** [comment] 2016-11-07 21:29
@tombro1987 I'm actively working on this issue now. I'd like to give it a little more time before we meet. NetLogo is now installed centrally and I have a PR in place for the documentation #436 

When you tried running the model on your machine, what exactly did you do? Run a  batch job? If so, where's the batch file please?

**Comment by philmikejones** [comment] 2016-11-08 09:55
@tombro1987 @mikecroucher We ran an experiment associated with Tom's model's behaviour space and used this guide (http://ccl.northwestern.edu/netlogo/docs/behaviorspace.html#advanced) to run it from the command line, modifying the example to match our installation and experiment.

**Comment by mikecroucher** [comment] 2016-11-08 13:24
Thanks Phil. I've got a copy of Tom's model. What was the command line you used? I want to be able to reproduce exactly what you did.

**Comment by tombro1987** [comment] 2016-11-08 16:06
Hi Mike. Thanks very much for all your help with the modelling. 

Here's the code we used:

```
java -Xmx6144m -Dfile.encoding=UTF-8 -cp NetLogo_5_2_0/NetLogo.jar 
org.nlogo.headless.Main \
--model Sheffield\ east\ model/test_model_ice.nlogo \
--experiment experiment \
--table -

```

we ran is using qrsh rather than qsub, so I don't know if that would make any difference?

**Comment by mikecroucher** [comment] 2016-11-08 17:14
Thanks. I was in the middle of building my own working example when you sent that so I've not yet tried it. The first problem that I can see is that you've not specified the number of threads. So, NetLogo will use the default. Unfortunately, the default is the number of CPUs that you have on the node -- which is 16 in most cases.  

Your interactive qrsh session will only have 1 core allocated to it and you'll be running 16 threads. It'll be slow at best.

At worst, you'll not have enough memory. You requested 6144 megabytes. I'm not sure if this is per-thread or not. If it is, you'll not have enough memory.

**Comment by mikecroucher** [comment] 2016-11-08 17:21
I've built an example based on one of the built in models.  To run it, log into Iceberg and start a `qrsh` session. Then do the following to get access to a more recent version of git

    module load apps/gcc/5.2/git/2.5

Download my High Performance Computing examples repo with

   git clone https://github.com/mikecroucher/HPC_Examples

Go to the netlogo example. This is currently at 

    cd HPC_Examples/apps/netlogo/

It contains a .nlogo model and a batch submission script.  Submit it with 

   sub submit_netlogo.sh 

The current script is configured to use 4 cores. You'll be able to go up to 16 but no more.
 
I'm playing with this example a little and will write it up in more detail in due course.

**Comment by mikecroucher** [comment] 2016-11-08 17:51
I tried my submission script on your model at it instantly failed with 

    java.lang.IllegalStateException: Can't find extension: gis/gis.jar

**Comment by mikecroucher** [comment] 2016-11-08 17:54
Others have seen this too 

http://netlogo-users.18673.x6.nabble.com/Extensions-in-Headless-mode-td4865994.html

I'm not loving the solution suggested in the above link. Makes it difficult to make decent use of centrally installed software.

**Comment by willfurnass** [comment] 2016-11-08 18:04
Does it help if you add the jar to the Java classpath? e.g.

```
export CLASSPATH=/some/path/gis/gis.jar:$CLASSPATH
runNetLogoStuff.sh
```

**Comment by mikecroucher** [comment] 2016-11-08 18:09
I'll give it a try but apparently not. https://groups.yahoo.com/neo/groups/netlogo-users/conversations/topics/13362

Seems I have to cd into the directory containing NetLogo for its extension manager to work. Testing this now.

**Comment by mikecroucher** [comment] 2016-11-08 18:10
Testing takes FOREVER. I'm only requesting 2 cores and i actually have to spend time in the queues :(

**Comment by mikecroucher** [comment] 2016-11-08 18:18
Of course if you `cd` to the centrally installed NetLogo, it attempts to dump the output to that directory and you get permission denied.  Fixed by asking it to output to the current working directory using the `$SGE_O_WORKDIR` environment variable.

So, my script now looks like this:

```
#!/bin/bash
#$ -l mem=3G
#$ -l rmem=3G
#Combine stderr and stdout into one file
#$ -j y
#Make sure that the value below matches the number of threads
#$ -pe openmp 2

module load apps/binapps/netlogo/5.3.1

#Makes sure this matches the number of openmp slots requested
threads=2
#Set the filename of the output csv file
output_table=out_$threads.csv
#Experiment and model names
experiment=experiment
model=Sheffield_east_test_modelV2.nlogo

echo "$threads threads requested"

cd $NETLOGO_DIR
time java -Xmx1024m -Dfile.encoding=UTF-8 -cp $NETLOGO_DIR/NetLogo.jar org.nlogo.headless.Main --model $SGE_O_WORKDIR/$model --experiment $experiment --table $SGE_O_WORKDIR/$output_table --threads $threads
```

and it craps out with 

    java.lang.IllegalStateException: Can't find extension: dynamic-scheduler/dynamic-scheduler.jar

/me is playing ErrorMessage whack-a-mole

**Comment by mikecroucher** [comment] 2016-11-08 18:24
So I can't find that extension anywhere in the NetLogo install. My google-fu has discovered this: https://github.com/colinsheppard/Dynamic-Scheduler-Extension 

@tombro1987 Have you installed this on your own machine?

**Comment by mikecroucher** [comment] 2016-11-08 18:45
I took a punt and installed the dynamic-sheduler extension.  Did this:

```
wget https://github.com/colinsheppard/Dynamic-Scheduler-Extension/archive/v0.2.1.tar.gz
tar -xvzf ./v0.2.1.tar.gz 
mv Dynamic-Scheduler-Extension ./dynamic-scheduler
mv ./dynamic-scheduler/ /usr/local/packages6/apps/binapps/netlogo/netlogo-5.3.1-64/app/extensions/
```

Must add this to NetLogo install instructions.

**Comment by mikecroucher** [comment] 2016-11-08 18:46
It runs!

**Comment by mikecroucher** [comment] 2016-11-08 18:49
It dies! 

However, this time I think that the problem is that I don't have all of the input files.  Error message is 

    Run #2, RUNTIME ERROR: Extension exception: shapefile Sheffield_data/Sheffield_east_buffer.shp not found

@tombro1987 Did you give me all the files I need to run this?  In the google drive you sent me I have `Sheffield_east_test_modelV2.nlogo` but not `.shp` files

**Comment by tombro1987** [comment] 2016-11-09 14:46
@mikecroucher I did try the Dynamic Scheduler extension for my models, I think it needs to be downloaded and installed in the extension folder within the Netlogo application itself. I found the extension quite restrictive though and it didn't really execute the functions as I wanted it to. It might be worth another look though.

Apologies I thought I'd included all the shapefiles, is there an additional data folder along with the `Sheffield_east_test_modelV2.nlogo` file? If not I can send again.

**Comment by mikecroucher** [comment] 2016-11-10 16:04
@tombro1987 You were right. You sent the data!

I think I have everything working. On iceberg, go to `/fastdata/fe1mpc/public/sheffield_east` where you will find a submission script along with your model and the data.

I suggest that you copy this to your home directory. e.g.

`cp -r /fastdata/fe1mpc/public/sheffield_east/ ~/`

Submit the job with

`qsub submit_netlogo.sh`

The submission script is currently set to 4 cores which should start relatively quickly. You can go up to 16 cores but doing so will cause you to be stuck in the queue for a few hours. Might be worth it though! Depends how your job parallelises.

There seems to be a problem with your model though. The output file contains **millions** of these error messages

```
Run #4, RUNTIME ERROR: ASK expected input to be an agent or agentset but got NOBODY instead.
error while patch -7 1 running ASK
  called by procedure VENICE-SETUP
  called by procedure SETUP
  called by procedure __EVALUATOR
```

This causes the output file to be several gigabytes in size -- all of which is error messages!

**Comment by tombro1987** [comment] 2016-11-14 14:07
@mikecroucher Thanks so much for that (and apologies for the late reply), will try giving it a go. Once I've fixed that rather frustrating error that is.

I don't remember coming across this before, out of interest I don't suppose the output files gave any indication as to how far through the simulation the error(s) occurred? No problem if not, either way I'll get onto trying to find a fix for that.

**Comment by mikecroucher** [comment] 2016-11-23 07:01
No worries @tombro1987 

I'd be very interested in the outcome and really hope that you get some decent speed ups.

**Comment by tombro1987** [comment] 2016-11-28 20:42
@mikecroucher I've managed to fix that error, so hopefully should be able to test the models out soon. Will let you know how it goes.

**Comment by mikecroucher** [comment] 2017-03-08 08:34
This is now complete as far as I know.

**Closed by mikecroucher** 2017-03-08 08:34 UTC
